In [1]:
def my_function():
    pass

In [2]:
def my_sq(x):
    return x ** 2

In [3]:
my_sq(4)

16

In [4]:
def avg_2(x, y):
    return (x + y) / 2

In [5]:
avg_2(10, 20)

15.0

In [6]:
assert avg_2(10, 20) == 15.0

In [7]:
import pandas as pd

In [8]:
df=pd.DataFrame({'a':[10,20,30],
                 'b':[20,30,40]})
df

a   b
0  10  20
1  20  30
2  30  40

In [9]:
df['a'] ** 2

0    100
1    400
2    900
Name: a, dtype: int64

In [10]:
type(df['a'])

pandas.core.series.Series

In [11]:
def my_sq(x):
    # assert isinstance(x, int)
    return x ** 2

In [12]:
df['a'].apply(my_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [13]:
def my_exp(x, e):
    return x ** e

In [14]:
my_exp(2, 2)

4

In [15]:
my_exp(2, 10)

1024

In [16]:
df['a'].apply(my_exp, e=10)

0        10000000000
1     10240000000000
2    590490000000000
Name: a, dtype: int64

In [17]:
def print_me(x):
    print(x)

In [18]:
df

a   b
0  10  20
1  20  30
2  30  40

In [19]:
df.apply(print_me, axis=0)

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [20]:
def avg_3(x, y, z):
    return (x + y + z) / 3

In [22]:
#df.apply(avg_3)
'''
TypeError: avg_3() missing 2 required positional arguments: 'y' and 'z'
Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...
'''

"\nTypeError: avg_3() missing 2 required positional arguments: 'y' and 'z'\nOutput is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...\n"

In [23]:
def avg_3_apply(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return (x + y + z) / 3

In [24]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [25]:
import numpy as np

In [26]:
df.apply(np.mean)

a    20.0
b    30.0
dtype: float64

In [28]:
#df.apply(avg_3_apply, axis=1)
'''
IndexError: index 2 is out of bounds for axis 0 with size 2
Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...
'''

'\nIndexError: index 2 is out of bounds for axis 0 with size 2\nOutput is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...\n'

In [29]:
df

a   b
0  10  20
1  20  30
2  30  40

In [30]:
def avg_2_apply(row):
    x = row[0]
    y = row[1]
    return (x + y) / 2

In [31]:
df.apply(avg_2_apply, axis=1)

C:\Users\treme\AppData\Local\Temp\ipykernel_13208\646818405.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  x = row[0]
C:\Users\treme\AppData\Local\Temp\ipykernel_13208\646818405.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  y = row[1]


0    15.0
1    25.0
2    35.0
dtype: float64

In [32]:
import seaborn as sns

In [33]:
titanic = sns.load_dataset('titanic')

In [34]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [35]:
def count_missing(vec):
    """Counts the number of missing values in a vector
    """
    null_vec = pd.isnull(vec)
    null_count = np.sum(null_vec)
    return null_count

In [36]:
count_missing?

Signature: count_missing(vec)
Docstring:
Counts the number of missing values in a vector
    
File:      c:\users\treme\appdata\local\temp\ipykernel_13208\3590789969.py
Type:      function

In [37]:
cmis_col = titanic.apply(count_missing)

In [38]:
cmis_col

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [39]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [40]:
cmis_row = titanic.apply(count_missing, axis=1)

In [41]:
cmis_row

0      1
1      0
2      1
3      0
4      1
      ..
886    1
887    0
888    2
889    0
890    1
Length: 891, dtype: int64

In [42]:
def avg_2(x, y):
    return (x + y) / 2

In [43]:
df

a   b
0  10  20
1  20  30
2  30  40

In [44]:
avg_2(df['a'], df['b'])

0    15.0
1    25.0
2    35.0
dtype: float64

In [45]:
(df['a'] + df['b']) / 2

0    15.0
1    25.0
2    35.0
dtype: float64

In [46]:
def avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [48]:
#avg_2_mod(df['a'], df['b'])
#ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [49]:
avg_2_mod(10, 20)

15.0

In [50]:
avg_2_mod(20, 30)

nan

In [51]:
import numpy as np

In [52]:
avg_2_mod_vec = np.vectorize(avg_2_mod)

In [53]:
df

a   b
0  10  20
1  20  30
2  30  40

In [54]:
avg_2_mod_vec(df['a'], df['b'])

array([15., nan, 35.])

In [55]:
@np.vectorize
def v_avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [56]:
v_avg_2_mod(df['a'], df['b'])

array([15., nan, 35.])

In [58]:
import numba

In [59]:
@numba.vectorize
def v_avg_2_mod_numba(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [60]:
v_avg_2_mod_numba(df['a'].values, df['b'].values)

array([15., nan, 35.])

In [61]:
%%timeit
avg_2(df['a'], df['b'])

112 µs ± 1.22 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [62]:
%%timeit
v_avg_2_mod(df['a'], df['b'])

30.4 µs ± 521 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [63]:
%%timeit
v_avg_2_mod_numba(df['a'].values, df['b'].values)

7.04 µs ± 928 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
