In [1]:
import pandas as pd

In [2]:
import seaborn as sns

In [3]:
tips = sns.load_dataset('tips')

In [4]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [7]:
import statsmodels.formula.api as smf

In [8]:
model = smf.ols('tip ~ total_bill', data=tips)

In [9]:
results = model.fit()

In [10]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    tip   R-squared:                       0.457
Model:                            OLS   Adj. R-squared:                  0.454
Method:                 Least Squares   F-statistic:                     203.4
Date:                Sat, 09 Dec 2023   Prob (F-statistic):           6.69e-34
Time:                        17:36:29   Log-Likelihood:                -350.54
No. Observations:                 244   AIC:                             705.1
Df Residuals:                     242   BIC:                             712.1
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.9203      0.160      5.761      0.000       0.606       1.235
total_bill     0.1050      0.007     14.260      0.000       0.091       0.120
==============================================================================
Omnibus:                       20.185   Durbin-Watson:                   2.151
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               37.750
Skew:                           0.443   Prob(JB):                     6.35e-09
Kurtosis:                       4.711   Cond. No.                         53.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [11]:
results.params

Intercept     0.920270
total_bill    0.105025
dtype: float64

In [14]:
from sklearn import linear_model

In [15]:
lr = linear_model.LinearRegression()

In [17]:
#predicted = lr.fit(X=tips['total_bill'], y=tips['tip'])
#Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...

In [18]:
predicted = lr.fit(X=tips['total_bill'].values.reshape(-1, 1),
                   y=tips['tip'])

In [19]:
predicted.coef_

array([0.10502452])

In [20]:
predicted.intercept_

0.9202696135546731

In [21]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [22]:
model = smf.ols('tip ~ total_bill + sex', data=tips).fit()

In [23]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    tip   R-squared:                       0.457
Model:                            OLS   Adj. R-squared:                  0.452
Method:                 Least Squares   F-statistic:                     101.3
Date:                Sat, 09 Dec 2023   Prob (F-statistic):           1.18e-32
Time:                        17:38:39   Log-Likelihood:                -350.52
No. Observations:                 244   AIC:                             707.0
Df Residuals:                     241   BIC:                             717.5
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         0.9067      0.175      5.182      0.000       0.562       1.251
sex[T.Female]     0.0266      0.138      0.192      0.848      -0.246       0.299
total_bill        0.1052      0.007     14.110      0.000       0.091       0.120
==============================================================================
Omnibus:                       20.499   Durbin-Watson:                   2.149
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               38.652
Skew:                           0.447   Prob(JB):                     4.05e-09
Kurtosis:                       4.733   Cond. No.                         63.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [24]:
lr = linear_model.LinearRegression()

In [26]:
#predicted = lr.fit(tips[['total_bill', 'sex']], tips['tip'])
'''
ValueError: could not convert string to float: 'Female'
Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...
'''

"\nValueError: could not convert string to float: 'Female'\nOutput is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...\n"

In [27]:
tips_dummy = pd.get_dummies(tips[['total_bill', 'sex', 'tip']])

In [28]:
tips_dummy.head()

total_bill   tip  sex_Male  sex_Female
0       16.99  1.01     False        True
1       10.34  1.66      True       False
2       21.01  3.50      True       False
3       23.68  3.31      True       False
4       24.59  3.61     False        True

In [29]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [30]:
tips_dummy = pd.get_dummies(tips[['tip', 'total_bill', 'sex']], drop_first=True)
tips_dummy.head()

tip  total_bill  sex_Female
0  1.01       16.99        True
1  1.66       10.34       False
2  3.50       21.01       False
3  3.31       23.68       False
4  3.61       24.59        True

In [31]:
predicted = lr.fit(tips_dummy.iloc[:, 1:], tips_dummy['tip'])

In [32]:
predicted.coef_

array([0.10523236, 0.02660871])

In [33]:
tips_dummy.head()

tip  total_bill  sex_Female
0  1.01       16.99        True
1  1.66       10.34       False
2  3.50       21.01       False
3  3.31       23.68       False
4  3.61       24.59        True

In [34]:
from patsy import dmatrices

In [35]:
response, predictors = dmatrices('tip ~ total_bill + sex', data = tips)

In [36]:
#response

In [37]:
#predictors

In [38]:
predicted = lr.fit(predictors, response)

In [39]:
predicted.coef_

array([[0.        , 0.02660871, 0.10523236]])